# Generated by Django 5.2.7 on 2025-10-16 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField()),
                ("expected_return_date", models.DateField()),
                ("actual_return_date", models.DateField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrowings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-borrow_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["borrow_date"], name="borrowings__borrow__782e8c_idx"
                    ),
                    models.Index(
                        fields=["expected_return_date"],
                        name="borrowings__expecte_043715_idx",
                    ),
                    models.Index(
                        fields=["actual_return_date"],
                        name="borrowings__actual__08c961_idx",
                    ),
                    models.Index(
                        fields=["user"], name="borrowings__user_id_41c6e7_idx"
                    ),
                    models.Index(
                        fields=["book"], name="borrowings__book_id_59f626_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expected_return_date__gt", models.F("borrow_date"))
                        ),
                        name="bor_expected_gt_borrow",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actual_return_date__isnull", True),
                            ("actual_return_date__gte", models.F("borrow_date")),
                            _connector="OR",
                        ),
                        name="bor_actual_null_or_gte_borrow",
                    ),
                ],
            },
        ),
    ]
